export type Difficulty = "easy" | "medium" | "hard";
export type QuestionType = "pattern" | "sequence" | "analogy" | "text" | "oddone";

export interface Question {
  cat: number;
  type: QuestionType;
  diff: Difficulty;
  badge: string;
  time: number;
  text: string;
  grid?: string[];
  gridClass?: string;
  seq?: (string | number)[];
  w1?: string;
  w2?: string;
  w3?: string;
  missing?: string;
  opts: string[];
  ans: number;
  exp: string;
}

export const CATEGORIES = [
  { name: "Logical Reasoning", short: "Logic" },
  { name: "Verbal Intelligence", short: "Verbal" },
  { name: "Spatial Reasoning", short: "Spatial" },
  { name: "Numerical Ability", short: "Numerical" },
  { name: "Working Memory", short: "Memory" },
  { name: "Processing Speed", short: "Speed" },
];

export const ALL_QUESTIONS: Question[] = [
  // ── LOGICAL REASONING (9) ──
  { cat: 0, type: "pattern", diff: "easy", badge: "Pattern Matrix", time: 45,
    text: "What completes the pattern?",
    grid: ["🔴","🔵","🔴","🔵","🔴","🔵","🔴","🔵","?"], gridClass: "grid3",
    opts: ["🟢","🔴","🔵","🟡"], ans: 2,
    exp: "The grid alternates Red and Blue. The missing cell follows the Blue pattern." },
  { cat: 0, type: "sequence", diff: "easy", badge: "Number Sequence", time: 45,
    text: "What number comes next?",
    seq: [3, 6, 9, 12, "?"],
    opts: ["14","15","16","18"], ans: 1,
    exp: "Add 3 each time. 12 + 3 = 15." },
  { cat: 0, type: "pattern", diff: "easy", badge: "Shape Matrix", time: 45,
    text: "Which shape completes the matrix?",
    grid: ["◆","◆◆","◆◆◆","○","○○","○○○","▲","▲▲","?"], gridClass: "grid3",
    opts: ["▲","▲▲▲","▲▲▲▲","○○"], ans: 1,
    exp: "Each row has 1, 2, 3 shapes. Third row needs three triangles." },
  { cat: 0, type: "sequence", diff: "medium", badge: "Number Sequence", time: 40,
    text: "What comes next in the sequence?",
    seq: [2, 6, 18, 54, "?"],
    opts: ["108","162","216","148"], ans: 1,
    exp: "Multiply by 3 each time. 54 × 3 = 162." },
  { cat: 0, type: "sequence", diff: "medium", badge: "Letter Sequence", time: 40,
    text: "What letter comes next?",
    seq: ["A","C","F","J","?"],
    opts: ["M","N","O","P"], ans: 2,
    exp: "Gaps increase: +2, +3, +4, +5. J is 10th letter, next is 15th = O." },
  { cat: 0, type: "oddone", diff: "medium", badge: "Odd One Out", time: 40,
    text: "Which number does not belong?",
    opts: ["16","25","36","50"], ans: 3,
    exp: "16, 25, 36 are perfect squares (4², 5², 6²). 50 is not." },
  { cat: 0, type: "sequence", diff: "hard", badge: "Number Sequence", time: 35,
    text: "What comes next?",
    seq: [1, 1, 2, 3, 5, "?"],
    opts: ["7","8","9","10"], ans: 1,
    exp: "Fibonacci: each number is the sum of the two before it. 3 + 5 = 8." },
  { cat: 0, type: "oddone", diff: "hard", badge: "Odd One Out", time: 35,
    text: "Which does not belong with the others?",
    opts: ["121","144","169","196"], ans: 3,
    exp: "121=11², 144=12², 169=13² are squares of primes. 196=14² is the odd one out." },
  { cat: 0, type: "sequence", diff: "hard", badge: "Complex Sequence", time: 35,
    text: "Find the missing number: 3, 7, 13, 21, 31, ?",
    seq: [3, 7, 13, 21, 31, "?"],
    opts: ["41","43","45","47"], ans: 1,
    exp: "Differences: 4, 6, 8, 10, 12 — increasing by 2. 31 + 12 = 43." },

  // ── VERBAL INTELLIGENCE (9) ──
  { cat: 1, type: "analogy", diff: "easy", badge: "Word Analogy", time: 45,
    text: "Complete the analogy:", w1: "Hot", w2: "Cold", w3: "Day", missing: "?",
    opts: ["Sun","Night","Warm","Light"], ans: 1,
    exp: "Hot is the opposite of Cold. Day's opposite is Night." },
  { cat: 1, type: "text", diff: "easy", badge: "Odd Word Out", time: 40,
    text: "Which word does NOT belong with the others?",
    opts: ["Apple","Banana","Carrot","Mango"], ans: 2,
    exp: "Apple, Banana, Mango are fruits. Carrot is a vegetable." },
  { cat: 1, type: "analogy", diff: "easy", badge: "Word Analogy", time: 45,
    text: "Complete the analogy:", w1: "Fish", w2: "Water", w3: "Bird", missing: "?",
    opts: ["Feathers","Sky","Wings","Nest"], ans: 1,
    exp: "Fish lives in Water. Bird lives in the Sky." },
  { cat: 1, type: "text", diff: "medium", badge: "Synonym", time: 40,
    text: "Which word is closest in meaning to BENEVOLENT?",
    opts: ["Cruel","Generous","Timid","Ambitious"], ans: 1,
    exp: "Benevolent means well-meaning and kind — closest to Generous." },
  { cat: 1, type: "analogy", diff: "medium", badge: "Word Analogy", time: 40,
    text: "Complete the analogy:", w1: "Author", w2: "Novel", w3: "Composer", missing: "?",
    opts: ["Piano","Concert","Symphony","Lyrics"], ans: 2,
    exp: "An Author creates a Novel. A Composer creates a Symphony." },
  { cat: 1, type: "text", diff: "medium", badge: "Odd Word Out", time: 40,
    text: "Which word does NOT belong?",
    opts: ["Simile","Metaphor","Hyperbole","Paragraph"], ans: 3,
    exp: "Simile, Metaphor and Hyperbole are figures of speech. Paragraph is a structural unit." },
  { cat: 1, type: "text", diff: "hard", badge: "Antonym", time: 35,
    text: "Which word is most OPPOSITE to EPHEMERAL?",
    opts: ["Brief","Transient","Permanent","Fleeting"], ans: 2,
    exp: "Ephemeral means lasting a very short time. Its antonym is Permanent." },
  { cat: 1, type: "analogy", diff: "hard", badge: "Complex Analogy", time: 35,
    text: "Complete the analogy:", w1: "Cartographer", w2: "Maps", w3: "Lexicographer", missing: "?",
    opts: ["Words","Libraries","Grammar","Dictionaries"], ans: 3,
    exp: "A Cartographer makes Maps. A Lexicographer compiles Dictionaries." },
  { cat: 1, type: "text", diff: "hard", badge: "Logical Deduction", time: 35,
    text: "All roses are flowers. Some flowers fade quickly. Therefore:",
    opts: ["All roses fade quickly","Some roses may fade quickly","No roses fade quickly","Roses are not flowers"], ans: 1,
    exp: "All roses are flowers, and some flowers fade. So some roses may fade quickly." },

  // ── SPATIAL REASONING (8) ──
  { cat: 2, type: "text", diff: "easy", badge: "Mirror Image", time: 45,
    text: "Which is the mirror image of: ◧",
    opts: ["◧","◨","◩","◪"], ans: 1,
    exp: "The mirror image of a left-half filled square ◧ is a right-half filled square ◨." },
  { cat: 2, type: "text", diff: "easy", badge: "Rotation", time: 45,
    text: "A shape rotated 90° clockwise: ▲ becomes?",
    opts: ["▲","▶","▼","◀"], ans: 1,
    exp: "A triangle pointing up (▲), rotated 90° clockwise, points right (▶)." },
  { cat: 2, type: "pattern", diff: "easy", badge: "Pattern Matrix", time: 45,
    text: "What completes the spatial pattern?",
    grid: ["◼","◻","◼","◻","◼","◻","◼","◻","?"], gridClass: "grid3",
    opts: ["◻","◼","◈","○"], ans: 0,
    exp: "The grid strictly alternates filled and empty squares. The missing cell is empty: ◻" },
  { cat: 2, type: "text", diff: "medium", badge: "Cube Faces", time: 40,
    text: "A cube has 6 faces. If one face shows ●, what is the minimum number of faces NOT showing ●?",
    opts: ["3","4","5","2"], ans: 2,
    exp: "The cube has 6 faces. Only one face shows ●, so the remaining 5 faces do not show ●." },
  { cat: 2, type: "text", diff: "medium", badge: "Counting Shapes", time: 40,
    text: "How many squares are in a 4×4 grid (counting all sizes)?",
    opts: ["16","24","30","36"], ans: 2,
    exp: "1×1: 16, 2×2: 9, 3×3: 4, 4×4: 1. Total = 30 squares of all sizes." },
  { cat: 2, type: "text", diff: "medium", badge: "Folding", time: 40,
    text: "A square paper is folded in half twice then a corner is cut. When unfolded, how many holes appear?",
    opts: ["1","2","3","4"], ans: 3,
    exp: "Each fold doubles the cut. Folding twice creates 4 layers, so 1 cut = 4 holes." },
  { cat: 2, type: "text", diff: "hard", badge: "3D Rotation", time: 35,
    text: "If you look at a clock from behind, what time does 3:00 appear to show?",
    opts: ["3:00","9:00","6:00","12:00"], ans: 1,
    exp: "Seen from behind, left and right are mirrored. The 3 appears where the 9 is — so it shows 9:00." },
  { cat: 2, type: "text", diff: "hard", badge: "Spatial Logic", time: 35,
    text: "A room has 4 corners. A spider sits in each corner. Each spider sees 3 other spiders. How many spiders are there?",
    opts: ["4","8","12","16"], ans: 0,
    exp: "There are simply 4 spiders — one in each corner. Each sees the other 3." },

  // ── NUMERICAL ABILITY (9) ──
  { cat: 3, type: "text", diff: "easy", badge: "Arithmetic", time: 45,
    text: "What is 15% of 200?",
    opts: ["25","30","35","40"], ans: 1,
    exp: "15% of 200 = 0.15 × 200 = 30." },
  { cat: 3, type: "sequence", diff: "easy", badge: "Number Series", time: 45,
    text: "What comes next? 100, 90, 81, 73, 66, ?",
    seq: [100, 90, 81, 73, 66, "?"],
    opts: ["58","59","60","61"], ans: 2,
    exp: "Differences: 10, 9, 8, 7, 6. So 66 − 6 = 60." },
  { cat: 3, type: "text", diff: "easy", badge: "Fractions", time: 40,
    text: "Which fraction is largest?",
    opts: ["3/4","5/8","7/10","2/3"], ans: 0,
    exp: "3/4=0.75, 5/8=0.625, 7/10=0.70, 2/3=0.667. Largest is 3/4." },
  { cat: 3, type: "text", diff: "medium", badge: "Word Problem", time: 40,
    text: "A train travels 240 km in 3 hours. How long to travel 400 km at the same speed?",
    opts: ["4h","4.5h","5h","5.5h"], ans: 2,
    exp: "Speed = 240/3 = 80 km/h. Time = 400/80 = 5 hours." },
  { cat: 3, type: "text", diff: "medium", badge: "Percentages", time: 40,
    text: "A price rises 20% then falls 20%. Net change?",
    opts: ["0%","−4%","+4%","−2%"], ans: 1,
    exp: "100 × 1.2 = 120. Then 120 × 0.8 = 96. Net change = −4%." },
  { cat: 3, type: "sequence", diff: "medium", badge: "Number Series", time: 40,
    text: "Find the missing number: 4, 9, 25, 49, ?, 169",
    seq: [4, 9, 25, 49, "?", 169],
    opts: ["81","100","121","144"], ans: 2,
    exp: "Squares of primes: 2²=4, 3²=9, 5²=25, 7²=49, 11²=121, 13²=169." },
  { cat: 3, type: "text", diff: "hard", badge: "Algebra", time: 35,
    text: "If 3x + 7 = 22, what is 2x − 1?",
    opts: ["8","9","10","11"], ans: 1,
    exp: "3x = 15, x = 5. Then 2(5) − 1 = 9." },
  { cat: 3, type: "text", diff: "hard", badge: "Word Problem", time: 35,
    text: "A tank fills in 6h alone, empties in 4h alone. If both run simultaneously, what happens?",
    opts: ["Fills in 12h","Empties in 12h","Fills in 24h","Empties in 24h"], ans: 1,
    exp: "Fill rate: 1/6. Empty rate: 1/4. Net: 1/6 − 1/4 = −1/12. Tank empties in 12h." },
  { cat: 3, type: "text", diff: "hard", badge: "Probability", time: 35,
    text: "A bag has 3 red and 5 blue balls. Two are drawn without replacement. P(both red)?",
    opts: ["3/28","1/8","3/56","9/64"], ans: 0,
    exp: "P = (3/8) × (2/7) = 6/56 = 3/28." },

  // ── WORKING MEMORY (8) ──
  { cat: 4, type: "text", diff: "easy", badge: "Sequence Recall", time: 50,
    text: "Select the sequence in REVERSE order: 3 → 7 → 2 → 9",
    opts: ["9,2,7,3","3,7,2,9","7,2,9,3","2,9,3,7"], ans: 0,
    exp: "The sequence 3, 7, 2, 9 reversed is 9, 2, 7, 3." },
  { cat: 4, type: "text", diff: "easy", badge: "Digit Span", time: 50,
    text: "Which is the correct sequence: 5 → 1 → 8 → 4 → 2",
    opts: ["5,1,8,4,2","5,1,4,8,2","1,5,8,4,2","5,1,8,2,4"], ans: 0,
    exp: "The exact sequence was 5, 1, 8, 4, 2." },
  { cat: 4, type: "text", diff: "easy", badge: "Word Recall", time: 50,
    text: "Which word was NOT in this list: CHAIR — TABLE — LAMP — DOOR — WINDOW",
    opts: ["Table","Lamp","Carpet","Door"], ans: 2,
    exp: "CARPET was not in the original list. All others were." },
  { cat: 4, type: "text", diff: "medium", badge: "N-Back", time: 45,
    text: "In the series: 4, 7, 3, 7, 4, 2, 4 — which number appeared exactly 3 times?",
    opts: ["7","3","4","2"], ans: 2,
    exp: "4 appears at positions 1, 5, and 7 — exactly 3 times." },
  { cat: 4, type: "text", diff: "medium", badge: "Dual Task", time: 45,
    text: "Count the vowels in: INTELLIGENCE QUOTIENT",
    opts: ["7","8","9","10"], ans: 2,
    exp: "INTELLIGENCE has 5 vowels, QUOTIENT has 4. Total = 9 vowels." },
  { cat: 4, type: "text", diff: "medium", badge: "Sequence Recall", time: 45,
    text: "The letters were shown: K, B, M, F, T, R. What was the 4th letter?",
    opts: ["M","F","T","B"], ans: 1,
    exp: "K(1), B(2), M(3), F(4). The 4th letter was F." },
  { cat: 4, type: "text", diff: "hard", badge: "Complex Recall", time: 40,
    text: "Sequence: 8, 3, 6, 1, 9, 4. What is the sum of the 2nd and 5th numbers?",
    opts: ["10","11","12","13"], ans: 2,
    exp: "2nd number = 3. 5th number = 9. Sum = 3 + 9 = 12." },
  { cat: 4, type: "text", diff: "hard", badge: "Mental Manipulation", time: 40,
    text: "Take LISTEN. Rearrange the letters. Which word can you make?",
    opts: ["SILENT","TINSEL","ENLIST","All of the above"], ans: 3,
    exp: "LISTEN is an anagram of SILENT, TINSEL and ENLIST — all three are valid." },

  // ── PROCESSING SPEED (9) ──
  { cat: 5, type: "text", diff: "easy", badge: "Quick Comparison", time: 20,
    text: "Which pair is identical?",
    opts: ["TIGER / TIGER","TIGER / TIGRE","TIGAR / TIGER","TIGRE / TIGRE"], ans: 0,
    exp: "Only the first pair TIGER / TIGER is exactly identical." },
  { cat: 5, type: "text", diff: "easy", badge: "Rapid Calculation", time: 20,
    text: "7 × 8 = ?",
    opts: ["54","56","58","62"], ans: 1,
    exp: "7 × 8 = 56." },
  { cat: 5, type: "text", diff: "easy", badge: "Symbol Counting", time: 20,
    text: "Count the letter E in: EXPERIENCE BREEDS EXCELLENCE",
    opts: ["6","7","8","9"], ans: 2,
    exp: "E-X-P-E-R-I-E-N-C-E B-R-E-E-D-S E-X-C-E-L-L-E-N-C-E = 8 E's." },
  { cat: 5, type: "text", diff: "medium", badge: "Quick Comparison", time: 18,
    text: "Which number is different? 748392 / 748392 / 748329 / 748392",
    opts: ["1st","2nd","3rd","4th"], ans: 2,
    exp: "The 3rd number is 748329, while the others are 748392." },
  { cat: 5, type: "text", diff: "medium", badge: "Rapid Calculation", time: 18,
    text: "If you have €50 and spend €17.40, how much is left?",
    opts: ["€31.60","€32.40","€32.60","€33.60"], ans: 2,
    exp: "50.00 − 17.40 = 32.60." },
  { cat: 5, type: "text", diff: "medium", badge: "Symbol Matching", time: 18,
    text: "How many times does ★ appear? ☆★☆★★☆★☆★★☆★",
    opts: ["5","6","7","8"], ans: 2,
    exp: "Counting carefully: positions 2,4,5,7,9,10,12 = 7 stars." },
  { cat: 5, type: "text", diff: "hard", badge: "Rapid Calculation", time: 15,
    text: "What is 13 × 13?",
    opts: ["156","168","169","172"], ans: 2,
    exp: "13 × 13 = 169." },
  { cat: 5, type: "text", diff: "hard", badge: "Quick Comparison", time: 15,
    text: "Find the wrong equation: 12×4=48 | 15×3=45 | 11×5=56 | 9×6=54",
    opts: ["12×4=48","15×3=45","11×5=56","9×6=54"], ans: 2,
    exp: "11 × 5 = 55, not 56. That equation is wrong." },
  { cat: 5, type: "text", diff: "hard", badge: "Rapid Deduction", time: 15,
    text: "Anna is older than Ben. Ben is older than Clara. Clara is older than Dan. Who is youngest?",
    opts: ["Anna","Ben","Clara","Dan"], ans: 3,
    exp: "The order is Anna > Ben > Clara > Dan. Dan is the youngest." },
]
